/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VocabEntry = IDL.Record({
  'word' : IDL.Text,
  'definition' : IDL.Text,
});
export const VocabSet = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'entries' : IDL.Vec(VocabEntry),
});
export const GameResult = IDL.Record({
  'setName' : IDL.Text,
  'total' : IDL.Nat,
  'studentName' : IDL.Text,
  'score' : IDL.Nat,
  'setId' : IDL.Text,
  'timestamp' : IDL.Int,
  'gameType' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearGameResults' : IDL.Func([], [], []),
  'createVocabSet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(VocabEntry)],
      [],
      [],
    ),
  'deleteVocabSet' : IDL.Func([IDL.Text], [], []),
  'getVocabSet' : IDL.Func([IDL.Text], [VocabSet], ['query']),
  'listGameResults' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'listVocabSets' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'recordGameResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateVocabSet' : IDL.Func([IDL.Text, IDL.Vec(VocabEntry)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VocabEntry = IDL.Record({ 'word' : IDL.Text, 'definition' : IDL.Text });
  const VocabSet = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'entries' : IDL.Vec(VocabEntry),
  });
  const GameResult = IDL.Record({
    'setName' : IDL.Text,
    'total' : IDL.Nat,
    'studentName' : IDL.Text,
    'score' : IDL.Nat,
    'setId' : IDL.Text,
    'timestamp' : IDL.Int,
    'gameType' : IDL.Text,
  });
  
  return IDL.Service({
    'clearGameResults' : IDL.Func([], [], []),
    'createVocabSet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(VocabEntry)],
        [],
        [],
      ),
    'deleteVocabSet' : IDL.Func([IDL.Text], [], []),
    'getVocabSet' : IDL.Func([IDL.Text], [VocabSet], ['query']),
    'listGameResults' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'listVocabSets' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'recordGameResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateVocabSet' : IDL.Func([IDL.Text, IDL.Vec(VocabEntry)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };